# This is an example config of prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'dcmonitor'
    scrape_interval: 5s
    scrape_timeout: 10s
    target_groups:
      - targets: ['localhost:8075']